version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auditor
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    env_file:
      - .env.example
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/auditor
volumes:
  db_data:
