name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: |
          yamllint -d "{extends: default, rules: {line-length: {max: 140}}}" .github/workflows/*.yml infra/docker-compose.yml
